mock_warehouse:
  outputs:
    dev:
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('DBT_BIGQUERY_PROJECT') }}"
      threads: 1
      type: bigquery
  target: dev
