WITH FINAL AS (
    SELECT
        ID AS SOURCE_ORDER_ID,
        INVENTORY_ID AS SOURCE_INVENTORY_ID,
        CUSTOMER_ID AS SOURCE_CUSTOMER_ID,
        PRICE,
        STATUS,
        ORDER_DATE,
        MD5(CAST(ID AS STRING)) AS ORDER_ID
    FROM
        {{ ref('orders') }}
)

SELECT *
FROM
    FINAL
