WITH FINAL AS (
    SELECT
        CUSTOMER_ID,
        SOURCE_CUSTOMER_ID,
        CUSTOMER_NAME,
        SOURCE_CUSTOMER_COUNTRY_ID,
        CUSTOMER_COUNTRY_NAME,
        CUSTOMER_COUNTRY_ISO_CODE
    FROM
        {{ ref('stg_customers') }}
)

SELECT *
FROM
    FINAL
